# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8fdc6f6697f5a90580c6c6c1044293139b65abd208491f100bb92940d19e654d4cfda729081f1360d04022b6333a4e0ef43fe172093d870530eff4d0018734ad

test:
  secret_key_base: 3b27abd68733e7e2921d11d463d8bc673c44a5a3feac601d49c3817ee8c7d279e8b66d6b3410e1d283ed52f3a6d3fb68dfae5b79c21f1e9ac897d0f720e8e6c5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
